[package]
name = "borondns-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "borondns"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
borondns-core = { path = "../borondns-core", version = "0.9.0" }
borondns-server = { path = "../borondns-server", version = "0.9.0" }

[dev-dependencies]
getrandom.workspace = true
rcgen.workspace = true

[features]
default = []
af-xdp = ["borondns-server/af-xdp"]

[lints]
workspace = true
