[package]
name = "oxidedns-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
oxidedns-core = { path = "../crates/oxidedns-core" }

[[bin]]
name = "dns_datagram"
path = "fuzz_targets/dns_datagram.rs"
test = false
doc = false
bench = false

[[bin]]
name = "transfer_stream"
path = "fuzz_targets/transfer_stream.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tsig_message"
path = "fuzz_targets/tsig_message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "notify_edns_datagram"
path = "fuzz_targets/notify_edns_datagram.rs"
test = false
doc = false
bench = false
