#!/usr/bin/env python3
"""Check Appendix A has traceability coverage for every SRS requirement ID."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRS_PATH = ROOT / "docs" / "BoronDNS-Secondary-SRS-v0.9.1.md"
APPENDIX_PATH = ROOT / "docs" / "appendix-a-traceability-matrix.md"

ID_PATTERN = r"ODS-[A-Z]+(?:-[A-Z0-9]+)?-\d{3}"
SRS_DEF_RE = re.compile(rf"^\*\*({ID_PATTERN})\b", re.MULTILINE)
ID_RE = re.compile(ID_PATTERN)
FULL_RANGE_RE = re.compile(rf"({ID_PATTERN})\.\.({ID_PATTERN})")
SHORT_RANGE_RE = re.compile(r"(ODS-[A-Z]+(?:-[A-Z0-9]+)?)-(\d{3})\.\.-?(\d{3})")

BEGIN_MARKER = "<!-- BEGIN GENERATED REQUIREMENT COVERAGE -->"
END_MARKER = "<!-- END GENERATED REQUIREMENT COVERAGE -->"


def natural_key(requirement_id: str) -> tuple[str, int]:
    prefix, number = requirement_id.rsplit("-", 1)
    return prefix, int(number)


def family(requirement_id: str) -> str:
    return requirement_id.rsplit("-", 1)[0]


def expand_range(start: str, end: str) -> list[str]:
    start_prefix, start_number = start.rsplit("-", 1)
    end_prefix, end_number = end.rsplit("-", 1)
    if start_prefix != end_prefix:
        raise ValueError(f"range crosses requirement families: {start}..{end}")
    start_int = int(start_number)
    end_int = int(end_number)
    if end_int < start_int:
        raise ValueError(f"range has descending numeric bounds: {start}..{end}")
    return [f"{start_prefix}-{number:03d}" for number in range(start_int, end_int + 1)]


def srs_requirement_ids(text: str) -> list[str]:
    return sorted(set(SRS_DEF_RE.findall(text)), key=natural_key)


def appendix_requirement_cells(text: str) -> list[str]:
    cells: list[str] = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        columns = [column.strip() for column in line.strip().strip("|").split("|")]
        if not columns or columns[0] in {"Requirement ID", "---"}:
            continue
        if ID_RE.search(columns[0]):
            cells.append(columns[0])
    return cells


def covered_ids_from_cell(cell: str) -> set[str]:
    covered: set[str] = set()
    range_spans: list[tuple[int, int]] = []

    for match in FULL_RANGE_RE.finditer(cell):
        covered.update(expand_range(match.group(1), match.group(2)))
        range_spans.append(match.span())

    for match in SHORT_RANGE_RE.finditer(cell):
        if any(start <= match.start() and match.end() <= end for start, end in range_spans):
            continue
        prefix = match.group(1)
        covered.update(expand_range(f"{prefix}-{match.group(2)}", f"{prefix}-{match.group(3)}"))
        range_spans.append(match.span())

    without_ranges = list(cell)
    for start, end in range_spans:
        for index in range(start, end):
            without_ranges[index] = " "
    covered.update(ID_RE.findall("".join(without_ranges)))
    return covered


def coverage_map(cells: list[str]) -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = {}
    for cell in cells:
        for requirement_id in covered_ids_from_cell(cell):
            mapping.setdefault(requirement_id, [])
            if cell not in mapping[requirement_id]:
                mapping[requirement_id].append(cell)
    return mapping


def generated_section(srs_ids: list[str], mapping: dict[str, list[str]]) -> str:
    families: dict[str, list[str]] = {}
    for requirement_id in srs_ids:
        families.setdefault(family(requirement_id), []).append(requirement_id)

    lines = [
        BEGIN_MARKER,
        "",
        "## Generated Per-Requirement Coverage Index",
        "",
        "This section is generated by `scripts/check-appendix-a-traceability.py`.",
        "It lists every requirement definition found in SRS v0.9.1 and the Appendix",
        "A row or range that covers it. Coverage here means traceability presence",
        "only; status, evidence, and remaining gaps remain governed by the matrix",
        "rows above and must not be read as verification completion.",
        "",
        "| Requirement family | SRS-defined IDs | Appendix A coverage row or range |",
        "| --- | --- | --- |",
    ]

    for requirement_family, ids in families.items():
        id_text = ", ".join(f"`{requirement_id}`" for requirement_id in ids)
        coverage_cells = sorted(
            {cell for requirement_id in ids for cell in mapping.get(requirement_id, [])}
        )
        coverage_text = ", ".join(f"`{cell}`" for cell in coverage_cells)
        lines.append(f"| {requirement_family} | {id_text} | {coverage_text} |")

    lines.extend(["", END_MARKER])
    return "\n".join(lines)


def replace_generated_section(text: str, section: str) -> str:
    if BEGIN_MARKER in text or END_MARKER in text:
        start = text.find(BEGIN_MARKER)
        end = text.find(END_MARKER)
        if start == -1 or end == -1 or end < start:
            raise ValueError("generated coverage markers are unbalanced")
        end += len(END_MARKER)
        return f"{text[:start].rstrip()}\n\n{section}\n\n{text[end:].lstrip()}"

    insertion_heading = "## Architectural Invariants"
    insertion_index = text.find(insertion_heading)
    if insertion_index == -1:
        raise ValueError(f"could not find insertion point: {insertion_heading}")
    return f"{text[:insertion_index].rstrip()}\n\n{section}\n\n{text[insertion_index:]}"


def check_appendix(update: bool) -> int:
    srs_text = SRS_PATH.read_text(encoding="utf-8")
    appendix_text = APPENDIX_PATH.read_text(encoding="utf-8")
    srs_ids = srs_requirement_ids(srs_text)
    if not srs_ids:
        print(f"no SRS requirement IDs found in {SRS_PATH}", file=sys.stderr)
        return 1

    cells = appendix_requirement_cells(appendix_text)
    mapping = coverage_map(cells)
    srs_set = set(srs_ids)
    covered_set = set(mapping)
    missing = sorted(srs_set - covered_set, key=natural_key)
    extra = sorted(covered_set - srs_set, key=natural_key)

    if missing:
        print("Appendix A is missing coverage for SRS requirement IDs:", file=sys.stderr)
        for requirement_id in missing:
            print(f"  {requirement_id}", file=sys.stderr)
        return 1

    if extra:
        print("Appendix A coverage references IDs not defined in SRS v0.9.1:", file=sys.stderr)
        for requirement_id in extra:
            print(f"  {requirement_id}", file=sys.stderr)
        return 1

    section = generated_section(srs_ids, mapping)
    expected_text = replace_generated_section(appendix_text, section)
    if appendix_text != expected_text:
        if update:
            APPENDIX_PATH.write_text(expected_text, encoding="utf-8")
        else:
            print(
                "Appendix A generated coverage section is missing or stale; "
                "run scripts/check-appendix-a-traceability.py --update",
                file=sys.stderr,
            )
            return 1

    print(
        f"Appendix A coverage check passed: {len(srs_ids)} SRS requirement IDs "
        f"covered by {len(cells)} Appendix A rows/ranges"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the generated coverage section in Appendix A",
    )
    args = parser.parse_args()
    return check_appendix(args.update)


if __name__ == "__main__":
    raise SystemExit(main())
