pub const BUILD_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const BUILD_COMMIT: &str = env!("BORONDNS_BUILD_COMMIT");
pub const BUILD_RUST_VERSION: &str = env!("BORONDNS_BUILD_RUST_VERSION");
pub const BUILD_TIMESTAMP: &str = env!("BORONDNS_BUILD_TIMESTAMP");
